name: Release Automation
on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: The scale of the version bump required for semver compatibility
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
concurrency: release
jobs:
  release:
    name: "Release & Publish"
    runs-on: ubuntu-latest
    steps:
      - name: 🧮 Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ELEMENT_BOT_TOKEN }}

      - name: 🔧 Set up node environment
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest

      - name: 🛠️ Setup
        run: yarn install --pure-lockfile

      - name: 👊 Bump version
        run: |
          yarn version --no-git-tag-version --${{ github.event.inputs.version-bump }}
          git config --global user.name 'ElementRobot'
          git config --global user.email 'releases@riot.im'
          git commit -am "${{ github.event.inputs.version-bump }} version bump"
          git push

      - name: 🚀 Publish to npm
        id: npm-publish
        run: |
          npm publish --access public --provenance
          echo "version=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - name: 🧬 Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.npm-publish.outputs.version }}
          release_name: Release ${{ steps.npm-publish.outputs.version }}
          body: ${{ steps.npm-publish.outputs.version }} Release
          draft: false
          prerelease: false
